### ISSUE TITLE
Plug-in startup failure

### ISSUE THREAD

**Issue by ZeKunLi** [tvhong/incremental-reading#36]
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-15.0-arm64-arm-64bit

When loading Incremental Reading v4103:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/xxx/Library/Application Support/Anki2/addons21/935264945/__init__.py", line 17, in <module>
    from .main import ReadingManager
  File "/Users/xxx/Library/Application Support/Anki2/addons21/935264945/main.py", line 24, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'

**Comment by tvhong** [comment]
Hi,
The add-on you're using, 935264945, hasn't been maintained for 5 years.

Please try deleting that and install https://ankiweb.net/shared/info/999215520 instead.
